# Generated by Django 5.0.2 on 2025-06-07 13:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vendors", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fooditem",
            name="image",
            field=models.ImageField(
                upload_to="food_items/",
                validators=[
                    django.core.validators.RegexValidator(
                        message="Only jpg, jpeg, png and gif files are allowed.",
                        regex="^[a-zA-Z0-9_-]+\\.(jpg|jpeg|png|gif)$",
                    )
                ],
            ),
        ),
    ]
