# Generated by Django 5.0.2 on 2025-06-08 06:30

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vendors", "0002_alter_fooditem_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fooditem",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="food_items",
                to="vendors.foodcategory",
            ),
        ),
        migrations.AlterField(
            model_name="fooditem",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="food_images/",
                validators=[
                    django.core.validators.RegexValidator(
                        message="Only jpg, jpeg, png and gif files are allowed.",
                        regex="^[a-zA-Z0-9_-]+\\.(jpg|jpeg|png|gif)$",
                    )
                ],
            ),
        ),
    ]
